project:
  type: website

website:
  title: "ISSS608-Lesson Learning Site"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 0"
          href: "Handson_Ex/handson_ex00/Hands-on_Ex00.html"
        - text: "Hands-on Exercise 1"
          href: "Handson_Ex/handson_ex01/Hands-on_Ex01.html"
    - text: "In-class Exercise"
    - text: "Take-home Exercise"
    right:
      - href: index.qmd
        text: "Home"
      - about.qmd

format:
  html:
    theme:
      - pulse
    css: styles.css
    toc: true

editor: visual

