project:
  type: website

website:
  title: "ISSS608-Lesson Learning Site"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 0"
          href: "Handson_Ex/handson_ex00/Hands-on_Ex00.html"
        - text: "Hands-on Exercise 1"
          href: "Handson_Ex/handson_ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Handson_Ex/handson_ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3"
          href: "Handson_Ex/handson_ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4"
          href: "Handson_Ex/handson_ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exercise 5"
          href: "Handson_Ex/handson_ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 7"
          href: "Handson_Ex/handson_ex07/handson_Ex07.html"
        - text: "Hands-on Exercise 8"
          href: "Handson_Ex/handson_ex08/handson_Ex08.html"
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 4"
          href: "In-class_Ex/In-class_Ex4/In-class_Ex4.html"
        - text: "In-class Exercise 5"
          href: "In-class_Ex/In-class_Ex5/In-class_Ex5.html"
        - text: "In-class Exercise 7"
          href: "In-class_Ex/In-class_Ex7/In-class_Ex7.html"
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "Takehome_Ex/Take-home_Ex1/Take-home_Ex1.html"
        - text: "Take-home Exercise 2"
          href: "Takehome_Ex/Take-home_Ex2/take-home_Ex02.html"
    right:
      - href: index.qmd
        text: "Home"
      - about.qmd

format:
  html:
    theme:
      - pulse
    css: styles.css
    toc: true

editor: visual

